# Generated by Django 2.2.12 on 2020-04-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_trasheddocument'),
        ('mayan_barcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_ocr', models.BooleanField(default=True, verbose_name='Automatically queue newly created documents for barcode scan.')),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_settings', to='documents.DocumentType', verbose_name='Document type')),
            ],
            options={
                'verbose_name': 'Document type settings',
                'verbose_name_plural': 'Document types settings',
            },
        ),
    ]
