# Generated by Django 2.2.12 on 2020-04-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mayan_barcodes', '0002_documenttypesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttypesettings',
            old_name='auto_ocr',
            new_name='auto_scan',
        ),
    ]
